/**
 * Application Constants
 * Centralized location for all magic numbers and configuration defaults
 */

// API and Model Configuration
export const API_DEFAULTS = {
  MODEL: 'claude-sonnet-4-5-20250929',
  MAX_TOKENS: 8000,
};

// Token Limits and Pricing
export const TOKEN_LIMITS = {
  // Context window limits
  MAX_PROMPT_TOKENS: 180000, // Leave 20k buffer below 200k limit
  MAX_TOTAL_TOKENS: 200000,

  // Rate limiting
  MAX_TOKENS_PER_MINUTE: 25000, // Conservative buffer (30k limit - 5k safety margin)

  // Character to token estimation
  CHARS_PER_TOKEN: 4,
  TOOL_OVERHEAD_PER_TOOL: 100, // Estimated tokens per tool in schema
};

// Pricing (Claude Sonnet 4.5)
export const PRICING = {
  INPUT_TOKENS_PER_MILLION: 3.00,  // $3 per 1M input tokens
  OUTPUT_TOKENS_PER_MILLION: 15.00, // $15 per 1M output tokens
};

// Rate Limiting Configuration
export const RATE_LIMITING = {
  MIN_DELAY_BETWEEN_CALLS: 5000,    // 5 seconds minimum
  TOOL_EXECUTION_DELAY: 1000,       // 1 second after tool execution
  RATE_LIMIT_THRESHOLD: 0.7,        // 70% capacity threshold
  HIGH_USAGE_DELAY: 15000,          // 15 seconds when over threshold
  RATE_LIMIT_BUFFER: 2000,          // 2 second buffer for rate limit waits
  MAX_WAIT_TIME: 60000,             // Cap wait time at 60 seconds
  RATE_LIMIT_WINDOW: 60000,         // 1 minute rate limit window
};

// Retry Configuration
export const RETRY_CONFIG = {
  MAX_RETRIES: 5,
  RATE_LIMIT_INITIAL_BACKOFF: 30000,  // 30 seconds
  RATE_LIMIT_MAX_BACKOFF: 120000,     // 120 seconds (2 minutes)
  RATE_LIMIT_CLEAR_WINDOW: 65000,     // 65 seconds to ensure new minute window
  CONSECUTIVE_ERROR_RESET_THRESHOLD: 2,
};

// Message Truncation
export const MESSAGE_TRUNCATION = {
  MIN_RECENT_MESSAGES: 4,  // Keep at least last 4 messages (2 tool interaction pairs)
  AGGRESSIVE_TRUNCATION_LIMIT: 150000, // More aggressive truncation on retry
};

// Agent Execution
export const AGENT_EXECUTION = {
  DELAY_BETWEEN_AGENTS: 10000,       // 10 seconds between agents
  DELAY_BETWEEN_AGENTS_ON_ERROR: 3000, // 3 seconds when error occurs
  DELAY_FOR_SPECIFIC_AGENTS: 3000,   // 3 seconds for specific agent runs
};

// MCP Configuration
export const MCP_DEFAULTS = {
  CONNECTION_TIMEOUT: 30000,  // 30 seconds
  MAX_RETRIES: 3,
  RETRY_DELAY: 2000,          // 2 seconds initial delay
};

// Date Configuration
export const DATE_CONFIG = {
  DEFAULT_DAYS_BACK: 7,
  DATE_FORMAT_REGEX: /^\d{4}-\d{2}-\d{2}$/,
  ISO_DATE_FORMAT: 'YYYY-MM-DD',
};

// File Paths (relative to project root)
export const PATHS = {
  CONFIG_FILE: 'config.json',
  CONFIG_EXAMPLE: 'config.example.json',
  REPORTS_DIR: 'reports',
  AGENTS_DIR: 'agents',
  MANUAL_SOURCES_DIR: 'manual_sources',
};

// Frontend Configuration
export const FRONTEND = {
  PORT: 3001,
  MIN_INSIGHT_LENGTH: 20,
  MAX_INSIGHT_LENGTH: 200,
  MIN_SUMMARY_LENGTH: 20,
  MAX_INSIGHTS_TO_EXTRACT: 2,
  MAX_FILES_IN_ERROR: 20,
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  RATE_LIMIT: 429,
  SERVER_ERROR: 500,
};

// Error Types
export const ERROR_TYPES = {
  RATE_LIMIT_ERROR: 'rate_limit_error',
  INVALID_REQUEST_ERROR: 'invalid_request_error',
};

// Report Configuration
export const REPORT = {
  DEFAULT_NAME: 'weekly-report',
  FOOTER_TEXT: '*Report generated by Chief of Staff Agent System*\n*Powered by Claude and GitHub Copilot*',
};
